console.log("----------map ----------")
let empdata=new Map();
empdata.set("emp1",2074)
empdata.set("emp2",2077)
empdata.set("emp3",2073)
empdata.set("emp4",2075)
empdata.set("emp5",2076)
console.log(empdata)
empdata.delete("emp5");
console.log(empdata.keys())
console.log(empdata.values())
console.log(`the value of emp3 is:${empdata.get("emp3")} sizeof map is: ${empdata.size}`)
empdata.clear()
console.log(empdata.size)
console.log("----------set----------")
let students=new Set()
students.add({name:"raj",address:"21 Sawtooth Circle, Salt Lake City,ut, 84129  United States",gender:"male"});
students.add({name:"Meena",address:"4 Northside Road, Groveton,nh, 3582  United States",gender:"female"});
console.log(students)
console.log("-------date object---------")
let date=new Date()
console.log(`today's date is:${date}`)
console.log(`time: ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}`)
console.log(`month:${date.getMonth()+1}`)
console.log(`year:${date.getFullYear()}`)
console.log(`date:${date.getDate()}`)
